upload:
  folder:
    path: "/home/slj/projects/Cleonora-R.Miahkykh/uploads"

server:
  servlet:
    context-path: /admin
  port: 8082

spring:
  application:
    name: Prominada

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "0000"

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB


logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  level:
    file: INFO

file:
  upload:
    dir: "${user.dir}/uploads"
  temp:
    dir: "${user.dir}/temp-uploads"

delengine-key: "g4zcrpmdrp0kcpu3suarvbahbnfsrzca"
